CREATE TABLE DISCOUNTS(
    id_discount INTEGER PRIMARY KEY AUTOINCREMENT,
    status VARCHAR(64) NOT NULL,
    percentage INTEGER(3) NOT NULL
);

CREATE TABLE OFFERS(
    id_offer INTEGER PRIMARY KEY AUTOINCREMENT,
    status VARCHAR(64) NOT NULL
);

CREATE TABLE TAXES(
    id_taxes INTEGER PRIMARY KEY AUTOINCREMENT,
    percentage INTEGER(3) NOT NULL
);

CREATE TABLE ROLES(
    id_roles INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(64) NOT NULL 
);

CREATE TABLE COUNTRIES(
    id_country INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(64) NOT NULL 
);

CREATE TABLE INVOICE_STATUS(
    id_invoce_status INTEGER PRIMARY KEY AUTOINCREMENT,
    status VARCHAR(64) NOT NULL
);

CREATE TABLE PAYMENTS(
    id_payment INTEGER PRIMARY KEY AUTOINCREMENT,
    type VARCHAR(64) NOT NULL
);

CREATE TABLE CUSTOMERS(
    email VARCHAR(64) PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    age INTEGER(2) NOT NULL,
    password VARCHAR(64) NOT NULL,
    physical_address VARCHAR(64) NOT NULL,
    id_country INTEGER REFERENCES COUNTRIES(id_country),
    id_roles INTEGER REFERENCES ROLES(id_roles)
);

CREATE TABLE PRODUCTS(
    id_product INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(64) NOT NULL,
    details VARCHAR(64) NOT NULL,
    minimum_stock INTEGER NOT NULL,
    maximum_stock INTEGER NOT NULL,
    current_stock INTEGER NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    price_with_tax DECIMAL(10, 2) NOT NULL,
    id_discount INTEGER REFERENCES DISCOUNTS(id_discount),
    id_offer INTEGER REFERENCES OFFERS(id_offer)
);

CREATE TABLE PRODUCTS_CUSTOMERS(
    id_product INTEGER REFERENCES PRODUCTS(id_product),
    id_customer INTEGER REFERENCES CUSTOMERS(id_customer)
);

CREATE TABLE INVOICES(
    id_invoice INTEGER PRIMARY KEY AUTOINCREMENT,
    date DATE NOT NULL,
    total_to_pay DECIMAL(10, 2) NOT NULL,
    id_customer INTEGER REFERENCES CUSTOMERS(id_customer),
    id_payment INTEGER REFERENCES PAYMENTS(id_payment),
    id_invoice_status INTEGER REFERENCES INVOICE_STATUS(id_invoice_status)
);

CREATE TABLE ORDERS(
    id_order INTEGER PRIMARY KEY AUTOINCREMENT,
    detail VARCHAR(64) NOT NULL,
    amount INTEGER NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    id_invoice INTEGER REFERENCES INVOICES(id_invoice),
    id_product INTEGER REFERENCES PRODUCTS(id_product)
);


