CREATE TABLE COUNTRIES(
    id_country INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(64) NOT NULL
);

CREATE TABLE PRIORITIES(
    id_priority INTEGER PRIMARY KEY AUTOINCREMENT,
    type_name VARCHAR(64) NOT NULL
);

CREATE TABLE CONTACT_REQUEST(
    id_email VARCHAR(64) PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    detail VARCHAR(225) NOT NULL,
    physical_address VARCHAR(225) NOT NULL,
    id_country INTEGER REFERENCES COUNTRIES(id_country),
    id_priority INTEGER REFERENCES PRIORITIES(id_priority)
); 