CREATE TABLE COUNTRIES(
    id_country INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(64) NOT NULL
);

CREATE TABLE USERS(
    id_user INTEGER PRIMARY KEY AUTOINCREMENT,
    email VARCHAR(64) NOT NULL, 
    name VARCHAR(64) NOT NULL, 
    id_country INTEGER REFERENCES COUNTRIES(id_country)
);

